// Package-oriented board top for the complete TurboVLA model.
//
// The wide simulation top is intentionally kept for cycle-accurate replay.
// This wrapper is the implementation target: one tagged 64-bit host stream,
// one 64-bit DDR read stream and one 64-bit DDR write stream.  Descriptor
// addresses remain inside the AXI/DMA controller, so the physical pinout does
// not grow with the internal descriptor width.
`ifndef TVLA_COMPLETE_MODEL_PACKAGE_TOP_SV
`define TVLA_COMPLETE_MODEL_PACKAGE_TOP_SV
module tvla_complete_model_package_top #(
  parameter int ROWS = 16,
  parameter int PCOLS = 48,
  parameter int DESC_W = 512,
  parameter int DESC_ID_W = 16
) (
  input  logic clk,
  input  logic rst_n,

  // host_in_kind: 0 command, 1 activation, 2 weight,
  //                3 action low 64b, 4 action high 48b.
  input  logic [63:0] host_in_data,
  input  logic [2:0] host_in_kind,
  input  logic [15:0] host_desc_id,
  input  logic host_in_valid,
  output logic host_in_ready,
  input  logic host_feed_pulse,
  input  logic [3:0] host_drain_row,

  // host_out_kind: 0 action low, 1 action high, 2 completion/observation.
  output logic [63:0] host_out_data,
  output logic [2:0] host_out_kind,
  output logic host_out_valid,
  input  logic host_out_ready,
  output logic host_done,
  output logic [31:0] host_observe,

  // Narrow external DDR streams.  The internal AXI address/control state is
  // still generated by the complete-model memory subsystem.
  input  logic [63:0] ddr_read_data,
  input  logic ddr_read_valid,
  output logic ddr_read_ready,
  output logic [63:0] ddr_write_data,
  output logic ddr_write_valid,
  input  logic ddr_write_ready,
  input  logic ddr_write_resp_valid
);
  logic [63:0] cmd_word;
  logic cmd_valid, cmd_ready;
  logic desc_valid, desc_ready;
  logic [DESC_ID_W-1:0] desc_id;
  logic [15:0] desc_data;
  logic [63:0] activation_data, weight_data;
  logic activation_valid, activation_ready;
  logic weight_valid, weight_ready;
  logic [111:0] action_data;
  logic action_valid, action_ready;
  logic action_out_valid, action_out_ready;
  logic [111:0] action_target;
  logic action_gripper;
  logic [7:0] action_step;
  logic replay_done;
  logic [31:0] architecture_observe;
  logic [127:0] core_wdata;
  logic [15:0] core_wstrb;
  logic core_arvalid, core_arready;
  logic [63:0] core_araddr;
  logic [7:0] core_arlen;
  logic core_rvalid, core_rready, core_rlast;
  logic core_awvalid, core_awready;
  logic [63:0] core_awaddr;
  logic [7:0] core_awlen;
  logic core_wvalid, core_wready, core_wlast;
  logic core_bvalid, core_bready;

  assign cmd_word = host_in_data;
  assign desc_id = host_desc_id;
  // The package stream carries the compact descriptor sideband in its low
  // 16 bits; the full descriptor remains in the compiler-generated memory.
  assign desc_data = host_in_data[15:0];
  assign cmd_valid = host_in_valid && (host_in_kind == 3'd0);
  assign desc_valid = cmd_valid;
  assign activation_data = host_in_data;
  assign weight_data = host_in_data;
  assign activation_valid = host_in_valid && (host_in_kind == 3'd1);
  assign weight_valid = host_in_valid && (host_in_kind == 3'd2);

  always_comb begin
    case (host_in_kind)
      3'd0: host_in_ready = cmd_ready && desc_ready;
      3'd1: host_in_ready = activation_ready;
      3'd2: host_in_ready = weight_ready;
      3'd3, 3'd4: host_in_ready = !action_valid;
      default: host_in_ready = 1'b0;
    endcase
  end

  // Assemble one 112-bit action input from two tagged host beats.
  logic action_half;
  logic [63:0] action_low;
  logic [47:0] action_high;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      action_half <= 1'b0;
      action_low <= '0;
      action_high <= '0;
      action_valid <= 1'b0;
    end else begin
      if (host_in_valid && host_in_ready && host_in_kind == 3'd3) begin
        action_low <= host_in_data;
        action_half <= 1'b1;
        action_valid <= 1'b0;
      end
      if (host_in_valid && host_in_ready && host_in_kind == 3'd4 && action_half) begin
        action_high <= host_in_data[47:0];
        action_half <= 1'b0;
        action_valid <= 1'b1;
      end
      if (action_valid && action_ready) action_valid <= 1'b0;
    end
  end
  assign action_data = {action_high, action_low};

  // Serialize the 112-bit action result on the same host output stream.
  logic [1:0] action_word_index;
  assign action_out_ready = host_out_ready && action_out_valid &&
                            (action_word_index == 2'd1);
  assign host_out_valid = action_out_valid;
  assign host_out_kind = (action_word_index == 2'd0) ? 3'd0 : 3'd1;
  assign host_out_data = (action_word_index == 2'd0) ? action_target[63:0] :
                         {16'd0, action_target[111:64]};
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) action_word_index <= 2'd0;
    else if (action_out_valid && host_out_ready) begin
      if (action_word_index == 2'd0) action_word_index <= 2'd1;
      else action_word_index <= 2'd0;
    end
  end

  assign host_done = replay_done;
  assign host_observe = architecture_observe;

  // Keep the internal AXI address/control signals inside the wrapper.  The
  // external interface is a data stream for the board DMA bridge.
  assign core_arready = ddr_read_ready;
  assign core_rvalid = ddr_read_valid;
  assign core_rlast = ddr_read_valid;
  assign ddr_read_ready = core_rready;
  assign ddr_write_valid = core_wvalid;
  assign ddr_write_data = core_wdata[63:0];
  assign core_awready = ddr_write_ready;
  assign core_wready = ddr_write_ready;
  assign core_bvalid = ddr_write_resp_valid;

  tvla_complete_model_top #(
    .ROWS(ROWS), .PCOLS(PCOLS), .DESC_W(DESC_W), .DESC_ID_W(DESC_ID_W)
  ) u_core (
    .clk(clk), .rst_n(rst_n), .cmd_word(cmd_word), .cmd_valid(cmd_valid),
    .cmd_ready(cmd_ready), .desc_valid(desc_valid), .desc_ready(desc_ready),
    .desc_id(desc_id), .desc_data(desc_data),
    .activation_data(activation_data), .activation_valid(activation_valid),
    .activation_ready(activation_ready), .weight_data(weight_data),
    .weight_valid(weight_valid), .weight_ready(weight_ready),
    .feed_pulse(host_feed_pulse), .drain_row(host_drain_row),
    .action_data(action_data), .action_valid(action_valid),
    .action_ready(action_ready), .action_out_valid(action_out_valid),
    .action_out_ready(action_out_ready), .action_target(action_target),
    .action_gripper(action_gripper), .action_step(action_step),
    .replay_done(replay_done), .architecture_observe(architecture_observe),
    .m_axi_arvalid(core_arvalid), .m_axi_arready(core_arready),
    .m_axi_araddr(core_araddr), .m_axi_arlen(core_arlen),
    .m_axi_rvalid(core_rvalid), .m_axi_rdata({64'd0, ddr_read_data}),
    .m_axi_rlast(core_rlast), .m_axi_rready(core_rready),
    .m_axi_awvalid(core_awvalid), .m_axi_awready(core_awready),
    .m_axi_awaddr(core_awaddr), .m_axi_awlen(core_awlen),
    .m_axi_wvalid(core_wvalid), .m_axi_wready(core_wready),
    .m_axi_wdata(core_wdata), .m_axi_wstrb(core_wstrb),
    .m_axi_wlast(core_wlast), .m_axi_bvalid(core_bvalid),
    .m_axi_bready(core_bready)
  );
endmodule
`endif
