"""Verified reference records; publisher year retained (CoRL event year may differ)."""
from pathlib import Path
import json,datetime
P=Path(__file__).resolve().parents[1]
R=[]
def add(key,title,authors,venue,year,url,claim,doi='',core=True):
 R.append(dict(key=key,title=title,authors=authors,venue=venue,year=year,url=url,claim=claim,doi=doi,counts_toward_21=core,verified='2026-09-12',verification='Primary publisher, conference, or author record; see URL'))
add('rt2','RT-2: Vision-Language-Action Models Transfer Web Knowledge to Robotic Control','Brianna Zitkovich and others','Conference on Robot Learning (CoRL), PMLR 229',2023,'https://proceedings.mlr.press/v229/zitkovich23a.html','Vision-language pretraining transfers to robot action prediction.')
add('openvla','OpenVLA: An Open-Source Vision-Language-Action Model','Moo Jin Kim and Karl Pertsch and Siddharth Karamcheti and Ted Xiao and Ashwin Balakrishna and Suraj Nair and Rafael Rafailov and Ethan P. Foster and Pannag R. Sanketi and Quan Vuong and Thomas Kollar and Benjamin Burchfiel and Russ Tedrake and Dorsa Sadigh and Sergey Levine and Percy Liang and Chelsea Finn','Conference on Robot Learning (CoRL 2024), PMLR 270',2025,'https://proceedings.mlr.press/v270/kim25c.html','Open VLA integrates visual encoders and language backbone; model paper, not FPGA implementation.')
add('octo','Octo: An Open-Source Generalist Robot Policy','Dibya Ghosh and Homer Rich Walke and Karl Pertsch and Kevin Black and Oier Mees and Sudeep Dasari and Joey Hejna and Tobias Kreiman and Charles Xu and Jianlan Luo and You Liang Tan and Lawrence Yunliang Chen and Quan Vuong and Ted Xiao and Pannag R. Sanketi and Dorsa Sadigh and Chelsea Finn and Sergey Levine','Robotics: Science and Systems (RSS)',2024,'https://www.roboticsproceedings.org/rss20/p090.html','Generalist policy and heterogeneous robot data context.','10.15607/RSS.2024.XX.090')
add('diffpolicy','Diffusion Policy: Visuomotor Policy Learning via Action Diffusion','Cheng Chi and Siyuan Feng and Yilun Du and Zhenjia Xu and Eric Cousineau and Benjamin C. M. Burchfiel and Shuran Song','Robotics: Science and Systems (RSS)',2023,'https://roboticsproceedings.org/rss19/p026.html','Iterative denoising for visuomotor action generation.','10.15607/RSS.2023.XIX.026')
add('dit','Scalable Diffusion Models with Transformers','William Peebles and Saining Xie','IEEE/CVF International Conference on Computer Vision (ICCV)',2023,'https://openaccess.thecvf.com/content/ICCV2023/html/Peebles_Scalable_Diffusion_Models_with_Transformers_ICCV_2023_paper.html','Transformer backbone for diffusion; not a robot deployment result.')
add('ditpa','DiTPA: A DiT-Based Action Planner Accelerator Exploiting Action-Denoising-Multimodality Redundancy for Embodied Artificial Intelligence','Xin Zhao and Longke Yan and Jiancong Li and Yongkun Wu and Fengbin Tu','ACM/IEEE International Symposium on Computer Architecture (ISCA)',2026,'https://researchportal.hkust.edu.hk/en/publications/ditpa-a-dit-based-action-planner-accelerator-exploiting-actionden/','Action-planner redundancy, software-hardware organization; not full visual-language execution.','10.1109/ISCA66397.2026.00188')
add('libero','LIBERO: Benchmarking Knowledge Transfer for Lifelong Robot Learning','Bo Liu and Yifeng Zhu and Chongkai Gao and Yihao Feng and Qiang Liu and Yuke Zhu and Peter Stone','Advances in Neural Information Processing Systems (NeurIPS), Datasets and Benchmarks',2023,'https://proceedings.neurips.cc/paper_files/paper/2023/hash/8c3c666820ea055a77726d66fc7d447f-Abstract-Datasets_and_Benchmarks.html','Task-level robot benchmark; intended quality protocol only.')
add('robotwin','RoboTwin: Dual-Arm Robot Benchmark with Generative Digital Twins','Yao Mu and Tianxing Chen and Zanxin Chen and Shijia Peng and Zhiqian Lan and Zeyu Gao and Zhixuan Liang and Qiaojun Yu and Yude Zou and Mingkun Xu and Lunkai Lin and Zhiqiang Xie and Mingyu Ding and Ping Luo','IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)',2025,'https://openaccess.thecvf.com/content/CVPR2025/html/Mu_RoboTwin_Dual-Arm_Robot_Benchmark_with_Generative_Digital_Twins_CVPR_2025_paper.html','Dual-arm task benchmark; no success values transferred.')
add('attention','Attention Is All You Need','Ashish Vaswani and Noam Shazeer and Niki Parmar and Jakob Uszkoreit and Llion Jones and Aidan N. Gomez and Lukasz Kaiser and Illia Polosukhin','Advances in Neural Information Processing Systems (NeurIPS)',2017,'https://proceedings.neurips.cc/paper_files/paper/2017/hash/3f5ee243547dee91fbd053c1c4a845aa-Abstract.html','QK/softmax/PV structure and dense projections.')
add('vit','An Image Is Worth 16x16 Words: Transformers for Image Recognition at Scale','Alexey Dosovitskiy and Lucas Beyer and Alexander Kolesnikov and Dirk Weissenborn and Xiaohua Zhai and Thomas Unterthiner and Mostafa Dehghani and Matthias Minderer and Georg Heigold and Sylvain Gelly and Jakob Uszkoreit and Neil Houlsby','International Conference on Learning Representations (ICLR)',2021,'https://openreview.net/forum?id=YicbFdNTTy','Visual tokens also produce Transformer matrix operators.')
add('flash','FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness','Tri Dao and Dan Fu and Stefano Ermon and Atri Rudra and Christopher Re','Advances in Neural Information Processing Systems (NeurIPS)',2022,'https://proceedings.neurips.cc/paper/2022/hash/67d57c32e20fd0a7a302cb81d36e40d5-Abstract-Conference.html','Exact attention can be accelerated by changing data movement rather than arithmetic.')
add('smooth','SmoothQuant: Accurate and Efficient Post-Training Quantization for Large Language Models','Guangxuan Xiao and Ji Lin and Mickael Seznec and Hao Wu and Julien Demouth and Song Han','International Conference on Machine Learning (ICML), PMLR 202',2023,'https://proceedings.mlr.press/v202/xiao23c.html','Activation-aware scaling for W8A8 quantization; no robot-quality guarantee.')
add('awq','AWQ: Activation-aware Weight Quantization for On-Device LLM Compression and Acceleration','Ji Lin and Jiaming Tang and Haotian Tang and Shang Yang and Wei-Ming Chen and Wei-Chen Wang and Guangxuan Xiao and Xingyu Dang and Chuang Gan and Song Han','Conference on Machine Learning and Systems (MLSys)',2024,'https://proceedings.mlsys.org/paper_files/paper/2024/hash/42a452cbafa9dd64e9ba4aa95cc1ef21-Abstract-Conference.html','Weight-only quantization addresses a different precision path from integer activation execution.')
add('gptq','GPTQ: Accurate Post-Training Quantization for Generative Pre-trained Transformers','Elias Frantar and Saleh Ashkboos and Torsten Hoefler and Dan Alistarh','International Conference on Learning Representations (ICLR)',2023,'https://github.com/ist-daslab/gptq','Post-training weight quantization; independent task quality evaluation remains needed.')
add('tvm','TVM: An Automated End-to-End Optimizing Compiler for Deep Learning','Tianqi Chen and Thierry Moreau and Ziheng Jiang and Lianmin Zheng and Eddie Yan and Haichen Shen and Meghan Cowan and Leyuan Wang and Yuwei Hu and Luis Ceze and Carlos Guestrin and Arvind Krishnamurthy','USENIX Symposium on Operating Systems Design and Implementation (OSDI)',2018,'https://www.usenix.org/conference/osdi18/presentation/chen','Graph/tensor compilation and target mapping.')
add('ansor','Ansor: Generating High-Performance Tensor Programs for Deep Learning','Lianmin Zheng and Chengfan Jia and Minmin Sun and Zhao Wu and Cody Hao Yu and Ameer Haj-Ali and Yida Wang and Jun Yang and Danyang Zhu and Koushik Sen and Joseph E. Gonzalez and Ion Stoica','USENIX Symposium on Operating Systems Design and Implementation (OSDI)',2020,'https://www.usenix.org/conference/osdi20/presentation/zheng','Automated tensor schedule search; not FPGA descriptor semantics.')
add('maestro','Understanding Reuse, Performance, and Hardware Cost of DNN Dataflow: A Data-Centric Approach','Hyoukjun Kwon and Prasanth Chatarasi and Michael Pellauer and Angshuman Parashar and Vivek Sarkar and Tushar Krishna','IEEE/ACM International Symposium on Microarchitecture (MICRO)',2019,'https://users.cs.duke.edu/~lkw34/papers/maestro-micro2019.pdf','Mapping-dependent reuse, occupancy and cost.')
add('eyeriss','Eyeriss: A Spatial Architecture for Energy-Efficient Dataflow for Convolutional Neural Networks','Yu-Hsin Chen and Joel Emer and Vivienne Sze','ACM/IEEE International Symposium on Computer Architecture (ISCA)',2016,'https://eems.mit.edu/wp-content/uploads/2016/04/eyeriss_isca_2016.pdf','Data reuse must be matched to spatial architecture.')
add('bitfusion','Bit Fusion: Bit-Level Dynamically Composable Architecture for Accelerating Deep Neural Networks','Hardik Sharma and Jongse Park and Naveen Suda and Liangzhen Lai and Benson Chau and Vikas Chandra and Hadi Esmaeilzadeh','ACM/IEEE International Symposium on Computer Architecture (ISCA)',2018,'https://cseweb.ucsd.edu/~hadi/doc/paper/2018-isca-bitfusion.pdf','Bit-level composition for precision-scalable hardware, distinct from fixed DSP packing.','10.1109/ISCA.2018.00069')
add('tpu','In-Datacenter Performance Analysis of a Tensor Processing Unit','Norman P. Jouppi and others','ACM/IEEE International Symposium on Computer Architecture (ISCA)',2017,'https://research.google/pubs/in-datacenter-performance-analysis-of-a-tensor-processing-unit/','Matrix array peak alone does not determine workload utilization.')
add('eie','EIE: Efficient Inference Engine on Compressed Deep Neural Network','Song Han and Xingyu Liu and Huizi Mao and Jing Pu and Ardavan Pedram and Mark A. Horowitz and William J. Dally','ACM/IEEE International Symposium on Computer Architecture (ISCA)',2016,'https://hanlab.mit.edu/projects/eie','Compressed sparse matrix-vector execution, not dense VLA scheduling.')
add('scnn','SCNN: An Accelerator for Compressed-sparse Convolutional Neural Networks','Angshuman Parashar and Minsoo Rhu and Anurag Mukkara and Antonio Puglielli and Rangharajan Venkatesan and Brucek Khailany and Joel Emer and Stephen W. Keckler and William J. Dally','ACM/IEEE International Symposium on Computer Architecture (ISCA)',2017,'https://research.nvidia.com/publication/2017-06_scnn-accelerator-compressed-sparse-convolutional-neural-networks','Sparse representations require matching delivery and accumulation hardware.')
add('finn','FINN: A Framework for Fast, Scalable Binarized Neural Network Inference','Yaman Umuroglu and Nicholas J. Fraser and Giulio Gambardella and Michaela Blott and Philip Leong and Magnus Jahre and Kees Vissers','ACM/SIGDA International Symposium on Field-Programmable Gate Arrays (FPGA)',2017,'https://arxiv.org/abs/1612.07119','Streaming low-precision FPGA mapping framework.','10.1145/3020078.3021744',False)
add('flight','FlightLLM: Efficient Large Language Model Inference with a Complete Mapping Flow on FPGAs','Shulin Zeng and Jun Liu and Guohao Dai and Xinhao Yang and Tianyu Fu and Hongyi Wang and Wenheng Ma and Hanbo Sun and Shiyao Li and Zixiao Huang and Yadong Dai and Jintao Li and Zehao Wang and Ruoyu Zhang and Kairui Wen and Xuefei Ning and Yu Wang','ACM/SIGDA International Symposium on Field-Programmable Gate Arrays (FPGA)',2024,'https://arxiv.org/abs/2401.03868','LLM FPGA mapping including configurable DSP chains and memory organization.',core=False)
add('quasar','Quasar-ViT: Hardware-Oriented Quantization-Aware Architecture Search for Vision Transformers','Zhengang Li and Alec Lu and Yanyue Xie and Zhenglun Kong and Mengshu Sun and Hao Tang and Zhong Jia Xue and Peiyan Dong and Caiwen Ding and Yanzhi Wang and Xue Lin and Zhenman Fang','ACM International Conference on Supercomputing (ICS)',2024,'https://arxiv.org/abs/2407.18175','Joint ViT quantization/model search and FPGA realization.',core=False)
add('packing','DSP-Packing: Squeezing Low-precision Arithmetic into FPGA DSP Blocks','Jan Sommer and M. Akif Ozkan and Oliver Keszocze and Jurgen Teich','International Conference on Field-Programmable Logic and Applications (FPL)',2022,'https://arxiv.org/abs/2203.11028','Packing extraction/correction and exact versus approximate packing.','10.1109/FPL57034.2022.00035',False)
add('timeloop','Timeloop: A Systematic Approach to DNN Accelerator Evaluation','Angshuman Parashar and Priyanka Raina and Yakun Sophia Shao and Yu-Hsin Chen and Victor A. Ying and Anurag Mukkara and Rangharajan Venkatesan and Brucek Khailany and Stephen W. Keckler and Joel Emer','IEEE International Symposium on Performance Analysis of Systems and Software (ISPASS)',2019,'https://research.nvidia.com/publication/2019-03_timeloop-systematic-approach-dnn-accelerator-evaluation','Architecture and mapping must be compared jointly.',core=False)
add('gemmini','Gemmini: Enabling Systematic Deep-Learning Architecture Evaluation via Full-Stack Integration','Hasan Genc and Seah Kim and Alon Amid and Ameer Haj-Ali and Vighnesh Iyer and Pranav Prakash and Jerry Zhao and Daniel Grubb and Harrison Liew and Howard Mao and Albert Ou and Colin Schmidt and Samuel Steffl and John Wright and Ion Stoica and Jonathan Ragan-Kelley and Krste Asanovic and Borivoje Nikolic and Yakun Sophia Shao','ACM/IEEE Design Automation Conference (DAC)',2021,'https://ieee-ceda.org/media/gemmini-enabling-systematic-deep-learning-architecture-evaluation-full-stack-integration','Full-stack evaluation exposes SoC effects absent from isolated kernel tests.','10.1109/DAC18074.2021.9586216',False)
add('ug579','UltraScale Architecture DSP Slice User Guide (UG579), v1.11','{Xilinx}','Vendor documentation',2021,'https://docs.amd.com/api/khub/documents/pTysoma4TYgNH95BrY1Sbw/content','DSP48E2 27-bit preadder and 27x18 multiplier; not a research paper.',core=False)
lines=[]
for r in R:
 typ='manual' if r['key']=='ug579' else 'inproceedings'
 fields={'title':'{'+r['title']+'}','author':r['authors'],'year':str(r['year']),'url':r['url']}
 fields['organization' if typ=='manual' else 'booktitle']=r['venue']
 if r['doi']:fields['doi']=r['doi']
 lines.append('@'+typ+'{'+r['key']+',\n'+',\n'.join('  '+k+' = {'+v+'}' for k,v in fields.items())+'\n}\n')
(P/'references.bib').write_text('\n'.join(lines),encoding='utf8')
(P/'data/references_audit.json').write_text(json.dumps(R,ensure_ascii=False,indent=2),encoding='utf8')
now=datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
md=f'# 参考文献核验\n\n生成时间：{now}。核验完成日期：2026-09-12。\n\n共 {len(R)} 条引用，其中 {sum(x["counts_toward_21"] for x in R)} 篇按保守口径计入顶会论文要求。另有 6 篇正式领域会议论文和 1 份厂商文档，不用它们凑足 21 篇。无预印本冒充正式发表。作者自存档用于查阅时，以其中的正式接收/发表记录识别版本。\n\nCoRL 的会议年份与 PMLR 出版年份可能不同；OpenVLA 保留出版方的 2025 年，同时注明 CoRL 2024。长作者列表在 RT-2 和 TPU 中采用规范的 et al. 写法，完整名单见原始记录。\n\n|键|题名与核验链接|正式出版|计入21篇|支持的论点|\n|---|---|---|---|---|\n'
for r in R:md+=f'|{r["key"]}|[{r["title"]}]({r["url"]})|{r["venue"]}, {r["year"]}|{"是" if r["counts_toward_21"] else "另计"}|{r["claim"]}|\n'
md+='\n## 创新主张边界\n\nDiTPA 是动作规划器加速器；FlightLLM 面向语言模型；Quasar-ViT 面向视觉 Transformer；FINN 是低精度 FPGA 工具链；Gemmini 是通用 DNN 系统。它们不能单独证明本项目是首个完整 VLA FPGA。当前编译器仍有 HostOp，故正文未宣称所有算子均已在 FPGA 上执行，也未采用“first”优先权声明。后续应补查 2025–2026 具身 FPGA/机器人动作处理器与完整部署工作，结合 P0 覆盖审计再决定是否加入。\n'
(P/'2026-09-12_references_audit.md').write_text(md,encoding='utf8')
print(f'{len(R)} references; {sum(x["counts_toward_21"] for x in R)} core verified papers')
