from pathlib import Path
import re
P=Path(__file__).resolve().parents[1]
t=(P/'data/base_manuscript.tex').read_text(encoding='utf8')
t=t.replace('balance}', 'balance}\n\\usepackage{tabularx}')
t=t.replace('Representative RTL tests reduce amortized interface cycles per row group from 140.3 to 89.3 for $K=64$ and from 2096.3 to 1053.3 for $K=2049$.','New matched RTL tests use two row groups and four physical PE columns throughout: cycles fall from 179 to 160 at $K=5$ and from 4197 to 2137 at $K=2049$. The double-rate result is a behavioral cycle result, not a routed-frequency claim.')
t=t.replace('The project trace exposes three connected observations.','The project trace exposes three connected observations, summarized in Figure~\\ref{fig:codesign}.')
t=t.replace('The paper makes three contributions.',r'''Figure~\ref{fig:model} separates a policy call from the actions consumed by a controller. Table~\ref{tab:related} compares execution scope and implementation mechanisms rather than importing speedups from different diffusion models.

The paper makes three contributions.''')
insert=r'''
\fig{figures/core1_model.pdf}{fig:model}{1.0}{HoloBrain-0 dataflow and policy-call hierarchy. The configured RGB and depth Swin encoders use stage depths $[2,2,6,2]$, and the text encoder is BERT-base-uncased. The action decoder contains six repeated blocks; the recorded evaluation uses ten denoising steps and an execution chunk of up to 32 actions. Chunk length is not multiplied into policy-call frequency. Colored modules denote model roles, not exclusive FPGA placement: the current compiler partitions GEMMs and HostOp boundaries inside these modules. The camera inset is the existing local scene capture.}
\fig{figures/core2_codesign.pdf}{fig:codesign}{1.0}{Workload observations and corresponding compilation/scheduling and hardware mechanisms. C1 connects shape-dependent overhead to feed/readout scheduling. C2 connects contiguous output runs to burst service. C3 connects repeated bias correction to DSP preadder placement. All three numerical insets are generated from frozen evidence; C1 cycle share is a prediction. Column merging remains pending, and the current preadder double-rate engine has not closed timing.}
'''
t=t.replace('\\section{Background and Motivation}',insert+'\n\\section{Background and Motivation}',1)
# Align the three named challenges; delivery and readout remain the two C1 subcases.
t=t.replace('Observation 1: Short Reductions Pay a Large Fixed Cost','C1: Short Reductions Pay a Large Fixed Cost').replace('Observation 2: Delivery and Readout Need Different Remedies','C1: Delivery and Readout Need Different Remedies').replace('Observation 3: Fine-Grained Writes Limit System Benefit','C2: Fine-Grained Writes Limit System Benefit')
t=t.replace('\\section{Compilation and Execution Framework}',r'''\subsection{C3: Replicated Correction Logic Consumes Fabric}
Each original Pack2 PE performs external bias correction in fabric around a DSP multiplier. Removing that repeated correction reduces isolated PE synthesis from 121 to 103 LUTs (14.9\%) and a matched 48-PE strip from 6988 to 6124 LUTs (12.4\%). These are different hierarchy levels. The full-engine preadder synthesis snapshot reports 105500 LUTs in the single-rate variant and 130288 LUTs in the double-rate variant, but routed resource and power results remain pending. The latter has core-clock synthesis WNS of $-0.216$ ns at a 1.649 ns period, so it is excluded from any achieved-performance claim.

\section{Compilation and Execution Framework}''',1)
start=t.index('\\begin{table*}',t.index('\\section{Related Work}'));end=t.index('\\end{table*}',start)+len('\\end{table*}')
t=t[:start]+r'\input{tables/capabilities.tex}'+t[end:]
t=t.replace('Table~\\ref{tab:related} separates robot-model papers from hardware studies.','Table~\\ref{tab:related} separates embodied/diffusion engines from Transformer and general FPGA systems. Cambricon-D uses temporal differences and sign-mask dataflow~\\cite{camd}; Ditto combines temporal difference processing with dynamic execution selection~\\cite{ditto}; EXION exploits output sparsity and compaction~\\cite{exion}. Diff-DiT already combines differential DiT inference, low-bit FPGA arithmetic, and pipelined memory access~\\cite{diffdit}. Thus, neither low precision nor computation--memory overlap alone distinguishes this work. The proposed distinction is their integration with the traced VLA execution boundaries and an exact replacement of replicated Pack2 correction. Quasar-ViT explicitly retains normalization and activation on ARM, illustrating why a binary all-FPGA checkmark is misleading. Full-stack integration, as emphasized by Gemmini~\\cite{gemmini}, requires accounting for these boundaries.')
new=r'''
\subsection{Matched Policy Performance and Energy Protocol}
Figure~\ref{fig:policycompare} reserves the matched HoloBrain-0 comparison and separately displays available archived GEMM predictions. The evaluated input is \texttt{place\_empty\_cup}. GPU and FPGA runs must share checkpoint, observations, preprocessing, action-head steps, and tensor semantics. GPU software fake-quantization latency is not an INT8-kernel measurement; the archived Evo-1 V100 results are excluded. At collection time all four accessible V100 devices had resident processes belonging to other users, precluding uncontaminated GPU power collection.

For call $i$, latency $L_i$ includes required host boundaries and transfers. Policy-call frequency is $1/\overline{L}$; fixed-trajectory inference time is $\sum_i L_i$ over ordered replay observations. This sum excludes environment simulation and robot motion, and is not closed-loop task completion time. The separate stage report records visual encoding, language/interaction, and action-head intervals. Stage labels must not be renamed as robot tasks. Missing call and stage measurements remain null in the artifact.

Energy per call is $E_i=\int_{t_i}^{t_i+L_i}P(t)\,dt$, and aggregate efficiency is $N/\sum_i E_i$ calls/J. GPU-device power and FPGA-engine power cannot establish a full-platform comparison: the host, external memory, and other required components must have matching inclusion boundaries. The 8.321 W estimate in Figure~\ref{fig:powerboundary} belongs only to the routed v5 out-of-context engine. It is not assigned to new variants and is not multiplied by a newer schedule to manufacture energy results. A valid version-specific activity window is still required even for engine-only calls/J.

\fig{figures/core4_performance.pdf}{fig:policycompare}{1.0}{Matched performance/energy comparison status and separate historical schedule prediction. The empty panels intentionally show unavailable measurements, not zero-valued bars. Panel (c) reports only archived GEMM cycles; the hatched double-rate configuration assumes ideal clock delivery and is not the timing-failing preadder engine measured at an achieved frequency. No robot-task speedup or full-policy call rate is inferred from panel (c).}
\fig{figures/core4_power_boundary.pdf}{fig:powerboundary}{1.0}{Available power evidence: routed v5 engine-only estimate, split by Vivado categories. This is not a module runtime breakdown or a board measurement. It provides neither the complete FPGA-system energy nor the power of a later PE variant.}

\subsection{Equal-Workload Cumulative Cycle Experiment}
Figure~\ref{fig:matched} adds a new matched microbenchmark. Every configuration receives the same four descriptors, deterministic seed, quantization parameters, memory model, and two row groups ($M=32$). The array has four physical columns. All sixteen configuration--descriptor pairs pass full context-memory byte comparison. The retained sequence is original Pack2, snapshot overlap, dual readout, and ideal double-rate paired delivery. This test is intentionally separate from the older 48-column results with unequal startup amortization.

At $K=5$, baseline and double-rate variants require 179 and 160 interface cycles (10.6\% fewer); at $K=2049$, they require 4197 and 2137 cycles (49.1\% fewer). Overlap plus dual readout alone reduces the deep case only from 4197 to 4193 cycles. These results support the mechanism distinction: supplying operands dominates the deep case, while fixed overhead limits the short case. They do not establish steady-state large-array performance. The existing three-/four-group baseline event-handling issue is not repaired by this two-group experiment.

The burst writer and preadder are not yet present in this matched harness; no cumulative bar is extrapolated for them. Version-matched power reports are absent, leaving the energy panel empty. The preadder's demonstrated contribution remains area reduction, not a presumed speedup. A routed timing gate must pass before replacing cycle-only results with achievable latency. Legal column merging is admitted only after tensor-identity and byte-level equivalence checks.
\fig{figures/core5_ablation.pdf}{fig:matched}{1.0}{Equal-workload cumulative RTL cycle comparison over four shape classes, not four robot tasks. Ratios are calculated from complete descriptor start-to-done counts. The hatched series assumes ideal double-rate clocks. No configuration has matched power for this test, so normalized energy efficiency remains unavailable.}
'''
t=t.replace('\\subsection{Mechanism Ablation Across Representative Shapes}',new+'\n\\subsection{Archived Mechanism Results Across Representative Shapes}',1)
t=t.replace('Representative RTL tests reduce','Archived RTL tests reduce')
t=t.replace('\\pending{ABLATION} is the matched-workload individual and combined mechanism experiment.','\\pending{ABLATION} extends the new matched microbenchmark to the full array, burst writer, and preadder with viable timing and corresponding power.')
t=t.replace('Working manuscript --- September 12, 2026','Revision 2 --- September 12, 2026')
t=t.replace('but routed resource and power results remain pending.','The later single-rate routed report contains 104066 LUTs, 768 DSPs, and 7.043 W estimated engine power at a 3.298 ns period, with setup/hold slack of 0.034/0.014 ns. Relative to the archived v5 routed engine, LUTs and estimated power decrease by 12.1\\% and 15.4\\%, respectively. This is a historical-to-current, vectorless comparison, not a matched board-energy measurement.')
t=t.replace('The 8.321 W estimate in Figure~\\ref{fig:powerboundary} belongs only to the routed v5 out-of-context engine. It is not assigned to new variants and is not multiplied by a newer schedule to manufacture energy results.','Figure~\\ref{fig:powerboundary} compares the archived v5 engine estimate of 8.321 W with the newly received single-rate preadder engine estimate of 7.043 W. Both use the same nominal period, device, ambient temperature, and vectorless estimation method. They are separate report versions, not a controlled rerun with workload-annotated activity. Neither estimate is multiplied by a newer schedule to manufacture energy results.')
t=t.replace('Available power evidence: routed v5 engine-only estimate, split by Vivado categories. This is not a module runtime breakdown or a board measurement. It provides neither the complete FPGA-system energy nor the power of a later PE variant.','Available routed engine power estimates for archived v5 and single-rate v10 preadder, split by Vivado categories. Both use a 3.298 ns period and 25 degree C ambient temperature. The estimated total falls by 15.4\\%; no measured call-energy improvement is inferred. These categories are not module runtime fractions.')
t=t.replace('four physical PE columns throughout: cycles fall from 179 to 160','48 physical PE columns throughout: cycles fall from 399 to 228').replace('4197 to 2137','4329 to 2205')
t=t.replace('The array has four physical columns.','The array has 48 physical columns and 768 DSPs; the first three descriptors use 96 logical output columns, and the narrow case uses six. A four-column preliminary run is retained separately.')
t=t.replace('require 179 and 160 interface cycles (10.6\\% fewer)','require 399 and 228 interface cycles (42.9\\% fewer)').replace('require 4197 and 2137 cycles','require 4329 and 2205 cycles').replace('from 4197 to 4193 cycles','from 4329 to 4281 cycles')
t=t.replace('They do not establish steady-state large-array performance.','The two-group window includes startup and does not establish steady-state throughput. On the short case, overlap plus dual readout reduces 399 cycles to 256, demonstrating the importance of wide-output drain cost.')
t=t.replace('The burst writer and preadder are not yet present in this matched harness; no cumulative bar is extrapolated for them.','The burst writer is not yet present in this matched harness. A separate full-width preadder substitution repeats all sixteen cases against the same golden memory: every case passes with identical descriptor cycles. This paired check establishes no cycle penalty from the PE replacement under the tested clock model; it is not a complete burst-plus-preadder cumulative result.')
t=t.replace('Version-matched power reports are absent, leaving the energy panel empty.','Workload-matched power is not available for the cumulative sequence, leaving the energy panel empty.')
t=t.replace('At collection time all four accessible V100 devices had resident processes belonging to other users, precluding uncontaminated GPU power collection.','All four accessible V100 devices had resident processes belonging to other users. An explicitly authorized exploratory measurement uses the lightly occupied GPU 1 without disturbing those processes. Twelve FP32 forwards of archived real observation s000 average 404.9 ms (2.47 forwards/s), with mean shared-board telemetry of 99.7 W. The path retains the export-compatible MHA slow path and is not an optimized INT8 GPU baseline. This observation is episode 0000000 at time index 40, not the separate place-empty-cup scene. It includes internal preprocessing and ten denoising steps but excludes external observation preprocessing and action postprocessing. The model-configuration SHA-256 matches the paper configuration. Therefore, these results provide an exploratory reference, not a complete matched-policy speedup. Three separately instrumented forwards provide stage times; the action decoder dominates that GPU profile.')
t=t.replace('Missing call and stage measurements remain null in the artifact.','Complete policy-call and fixed-trajectory measurements remain null; the separately identified exploratory GPU stage profile is available.')
t=t.replace('Matched performance/energy comparison status and separate historical schedule prediction. The empty panels intentionally show unavailable measurements, not zero-valued bars. Panel (c) reports only archived GEMM cycles; the hatched double-rate configuration assumes ideal clock delivery and is not the timing-failing preadder engine measured at an achieved frequency. No robot-task speedup or full-policy call rate is inferred from panel (c).','Exploratory GPU measurement and separately scoped FPGA predictions. (a) Shared V100 FP32 model-forward mean and observed min/max over 12 calls on s000; FPGA full-forward values remain unavailable. (b) GPU stage times from three separately instrumented runs with synchronized boundaries; these are stages, not tasks. (c) Archived GEMM-only predictions; the hatched series assumes ideal double-rate delivery. Execution scopes differ across panels, so no cross-platform speedup or energy-efficiency ratio is calculated.')
t=t.replace(', The later single-rate', '. The later single-rate')
t=t.replace(r'The evaluated input is \texttt{place\_empty\_cup}.', r'The planned matched input is \texttt{place\_empty\_cup}; the exploratory GPU observation below is recorded separately.')
(P/'main.tex').write_text(t,encoding='utf8')
print('Manuscript updated')
