// Scalarised vector wrapper around Xilinx Floating-Point Operator IP.
//
// The vendor cores are generated by vivado/gen_fp16_ip.tcl.  One scalar IP
// is time-multiplexed across LANES, so the control contract remains one
// vector command while the implementation keeps the FP16 arithmetic exact
// to the selected Xilinx core.  Icarus uses the same handshake with the
// fixed-point reference slot when TVLA_USE_VENDOR_FP16 is not defined.
`ifndef TVLA_FP16_IP_VECTOR_SV
`define TVLA_FP16_IP_VECTOR_SV
module tvla_fp16_ip_vector #(
  parameter int LANES = 16,
  parameter int DW = 16
) (
  input logic clk,
  input logic rst_n,
  input logic in_valid,
  output logic in_ready,
  input logic [3:0] op_code,
  input logic [LANES*DW-1:0] a,
  input logic [LANES*DW-1:0] b,
  input logic [DW-1:0] param,
  output logic out_valid,
  input logic out_ready,
  output logic [LANES*DW-1:0] y
);
`ifndef TVLA_USE_VENDOR_FP16
  tvla_fp16_alu #(.LANES(LANES), .DW(DW)) u_reference (
    .clk(clk), .rst_n(rst_n), .in_valid(in_valid), .in_ready(in_ready),
    .op_code(op_code), .a(a), .b(b), .param($signed(param)),
    .out_valid(out_valid), .out_ready(out_ready), .y(y)
  );
`else
  localparam logic [3:0] OP_ADD  = 4'd0;
  localparam logic [3:0] OP_MUL  = 4'd2;
  localparam logic [3:0] OP_EXP  = 4'd3;
  localparam logic [3:0] OP_RECIP = 4'd4;
  localparam logic [3:0] OP_SQRT = 4'd8;
  localparam logic [1:0] S_IDLE = 2'd0;
  localparam logic [1:0] S_SEND = 2'd1;
  localparam logic [1:0] S_WAIT = 2'd2;
  localparam logic [1:0] S_OUT  = 2'd3;
  logic [1:0] state;
  logic [3:0] selected_op;
  logic [$clog2(LANES)-1:0] lane;
  logic [LANES*DW-1:0] a_r, b_r;
  logic [DW-1:0] param_r;
  logic [LANES*DW-1:0] y_r;

  logic add_valid, add_ready, add_result_valid, add_result_ready;
  logic mul_valid, mul_ready, mul_result_valid, mul_result_ready;
  logic div_valid, div_ready, div_result_valid, div_result_ready;
  logic exp_valid, exp_ready, exp_result_valid, exp_result_ready;
  logic sqrt_valid, sqrt_ready, sqrt_result_valid, sqrt_result_ready;
  logic [DW-1:0] add_result, mul_result, div_result, exp_result, sqrt_result;
  logic [DW-1:0] scalar_a, scalar_b, scalar_num;
  logic selected_ready, selected_result_valid;
  logic [DW-1:0] selected_result;
  logic send_fire, result_fire;

  assign in_ready = (state == S_IDLE);
  assign out_valid = (state == S_OUT);
  assign y = y_r;
  assign scalar_a = a_r[lane*DW +: DW];
  assign scalar_b = b_r[lane*DW +: DW];
  // FP16 1.0.  Reciprocal is implemented as 1.0 / x by the divider IP.
  assign scalar_num = 16'h3c00;

  assign add_valid = (state == S_SEND) && (selected_op == OP_ADD);
  assign mul_valid = (state == S_SEND) && (selected_op == OP_MUL);
  assign div_valid = (state == S_SEND) && (selected_op == OP_RECIP);
  assign exp_valid = (state == S_SEND) && (selected_op == OP_EXP);
  assign sqrt_valid = (state == S_SEND) && (selected_op == OP_SQRT);
  assign selected_ready = (selected_op == OP_ADD) ? add_ready :
                          (selected_op == OP_MUL) ? mul_ready :
                          (selected_op == OP_RECIP) ? div_ready :
                          (selected_op == OP_EXP) ? exp_ready : sqrt_ready;
  assign selected_result_valid = (selected_op == OP_ADD) ? add_result_valid :
                                 (selected_op == OP_MUL) ? mul_result_valid :
                                 (selected_op == OP_RECIP) ? div_result_valid :
                                 (selected_op == OP_EXP) ? exp_result_valid : sqrt_result_valid;
  assign selected_result = (selected_op == OP_ADD) ? add_result :
                           (selected_op == OP_MUL) ? mul_result :
                           (selected_op == OP_RECIP) ? div_result :
                           (selected_op == OP_EXP) ? exp_result : sqrt_result;
  assign send_fire = (state == S_SEND) && selected_ready;
  assign result_fire = (state == S_WAIT) && selected_result_valid;

  tvla_fp16_add u_add (
    .aclk(clk), .s_axis_a_tvalid(add_valid), .s_axis_a_tready(add_ready),
    .s_axis_a_tdata(scalar_a), .s_axis_b_tvalid(add_valid),
    .s_axis_b_tready(), .s_axis_b_tdata(scalar_b),
    .s_axis_operation_tvalid(add_valid), .s_axis_operation_tready(),
    .s_axis_operation_tdata(8'd0), .m_axis_result_tvalid(add_result_valid),
    .m_axis_result_tready(add_result_ready), .m_axis_result_tdata(add_result)
  );
  tvla_fp16_mul u_mul (
    .aclk(clk), .s_axis_a_tvalid(mul_valid), .s_axis_a_tready(mul_ready),
    .s_axis_a_tdata(scalar_a), .s_axis_b_tvalid(mul_valid),
    .s_axis_b_tready(), .s_axis_b_tdata(scalar_b),
    .m_axis_result_tvalid(mul_result_valid), .m_axis_result_tready(mul_result_ready),
    .m_axis_result_tdata(mul_result)
  );
  tvla_fp16_div u_div (
    .aclk(clk), .s_axis_a_tvalid(div_valid), .s_axis_a_tready(div_ready),
    .s_axis_a_tdata(scalar_num), .s_axis_b_tvalid(div_valid),
    .s_axis_b_tready(), .s_axis_b_tdata(scalar_a),
    .m_axis_result_tvalid(div_result_valid), .m_axis_result_tready(div_result_ready),
    .m_axis_result_tdata(div_result)
  );
  tvla_fp16_exp u_exp (
    .aclk(clk), .s_axis_a_tvalid(exp_valid), .s_axis_a_tready(exp_ready),
    .s_axis_a_tdata(scalar_a), .m_axis_result_tvalid(exp_result_valid),
    .m_axis_result_tready(exp_result_ready), .m_axis_result_tdata(exp_result)
  );
  tvla_fp16_sqrt u_sqrt (
    .aclk(clk), .s_axis_a_tvalid(sqrt_valid), .s_axis_a_tready(sqrt_ready),
    .s_axis_a_tdata(scalar_a), .m_axis_result_tvalid(sqrt_result_valid),
    .m_axis_result_tready(sqrt_result_ready), .m_axis_result_tdata(sqrt_result)
  );
  assign add_result_ready = (state == S_WAIT) && (selected_op == OP_ADD);
  assign mul_result_ready = (state == S_WAIT) && (selected_op == OP_MUL);
  assign div_result_ready = (state == S_WAIT) && (selected_op == OP_RECIP);
  assign exp_result_ready = (state == S_WAIT) && (selected_op == OP_EXP);
  assign sqrt_result_ready = (state == S_WAIT) && (selected_op == OP_SQRT);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= S_IDLE;
      selected_op <= OP_ADD;
      lane <= '0;
      a_r <= '0;
      b_r <= '0;
      param_r <= '0;
      y_r <= '0;
    end else begin
      case (state)
        S_IDLE: if (in_valid) begin
          a_r <= a;
          b_r <= b;
          param_r <= param;
          selected_op <= op_code;
          lane <= '0;
          state <= S_SEND;
        end
        S_SEND: if (send_fire) state <= S_WAIT;
        S_WAIT: if (result_fire) begin
          y_r[lane*DW +: DW] <= selected_result;
          if (lane == LANES-1) state <= S_OUT;
          else begin lane <= lane + 1'b1; state <= S_SEND; end
        end
        S_OUT: if (out_ready) state <= S_IDLE;
        default: state <= S_IDLE;
      endcase
    end
  end
`endif
endmodule
`endif
