// Package-oriented board top for the complete TurboVLA model.
//
// The wide simulation top is intentionally kept for cycle-accurate replay.
// This wrapper is the implementation target: one tagged 64-bit host stream,
// one 64-bit DDR read stream and one 64-bit DDR write stream.  Descriptor
// addresses remain inside the AXI/DMA controller, so the physical pinout does
// not grow with the internal descriptor width.
`ifndef TVLA_COMPLETE_MODEL_PACKAGE_TOP_V8_SV
`define TVLA_COMPLETE_MODEL_PACKAGE_TOP_V8_SV
module tvla_complete_model_package_top_v8 #(
  parameter int ROWS = 16,
  parameter int PCOLS = 48,
  parameter int DESC_W = 512,
  parameter int DESC_ID_W = 16
) (
  input  logic clk,
  input  logic rst_n,

  // host_in_kind: 0 command, 1 activation, 2 weight,
  //                3 action low 64b, 4 action high 48b,
  //                5 descriptor-sideband 64b beat,
  //                6 scale/bias load (two beats per entry),
  //                7 DMA write payload 64b beat.  Two kind-7 beats are
  //                packed into one internal 128-bit DMA stream beat.
  input  logic [63:0] host_in_data,
  input  logic [2:0] host_in_kind,
  input  logic [15:0] host_desc_id,
  input  logic host_in_valid,
  output logic host_in_ready,
  input  logic host_feed_pulse,
  input  logic [3:0] host_drain_row,

  // host_out_kind: 0 action low, 1 action high, 2 completion/observation.
  output logic [63:0] host_out_data,
  output logic [2:0] host_out_kind,
  output logic host_out_valid,
  input  logic host_out_ready,
  output logic host_done,
  output logic [31:0] host_observe,

  // Narrow external DDR streams.  The internal AXI address/control state is
  // still generated by the complete-model memory subsystem.
  input  logic [63:0] ddr_read_data,
  input  logic ddr_read_valid,
  output logic ddr_read_ready,
  output logic [63:0] ddr_write_data,
  output logic ddr_write_valid,
  input  logic ddr_write_ready,
  input  logic ddr_write_resp_valid
);
  logic [63:0] cmd_word;
  logic cmd_valid, cmd_ready;
  logic desc_valid, desc_ready;
  logic core_sideband_valid, core_sideband_ready, core_sideband_last;
  logic [2:0] sideband_beat;
  logic scale_half;
  logic [11:0] scale_index_latched;
  logic [15:0] scale_a_latched, scale_w_latched, scale_out_latched;
  logic core_scale_load_valid, core_scale_load_ready;
  logic [11:0] core_scale_load_index;
  logic [15:0] core_scale_load_a, core_scale_load_w, core_scale_load_out;
  logic signed [31:0] core_scale_load_bias;
  logic [DESC_ID_W-1:0] desc_id;
  logic [15:0] desc_data;
  logic [63:0] activation_data, weight_data;
  logic activation_valid, activation_ready;
  logic weight_valid, weight_ready;
  logic [111:0] action_data;
  logic action_valid, action_ready;
  logic action_out_valid, action_out_ready;
  logic [111:0] action_target;
  logic action_gripper;
  logic [7:0] action_step;
  logic replay_done;
  logic [31:0] architecture_observe;
  logic [127:0] core_wdata;
  logic [15:0] core_wstrb;
  logic core_arvalid, core_arready;
  logic [63:0] core_araddr;
  logic [7:0] core_arlen;
  logic core_rvalid, core_rready, core_rlast;
  logic [127:0] core_rdata;
  logic core_awvalid, core_awready;
  logic [63:0] core_awaddr;
  logic [7:0] core_awlen;
  logic core_wvalid, core_wready, core_wlast;
  logic core_bvalid, core_bready;
  // The package wrapper exposes the DMA payload on the existing tagged host
  // stream.  This keeps the board pin count at 64 bits while still allowing
  // real payloads to reach the DMA write channel and real DMA read payloads
  // to leave the chip.
  logic core_dma_stream_out_valid, core_dma_stream_out_ready;
  logic [127:0] core_dma_stream_out_data;
  logic core_dma_stream_in_valid, core_dma_stream_in_ready;
  logic [127:0] core_dma_stream_in_data;
  logic dma_input_valid, dma_input_half;
  logic [63:0] dma_input_low;
  logic [127:0] dma_input_data;
  logic dma_output_valid, dma_output_half;
  logic [127:0] dma_output_data;
  // v8 routes DMA_READ payloads into real CTX/WRAM writes when the descriptor
  // selects target 0/1.  Target 2 keeps the old host readback behavior.
  logic loader_start, loader_busy, loader_done;
  logic [1:0] loader_target;
  logic loader_stream_ready;
  logic loader_ctx_wr_en, loader_wram_wr_en;
  logic [9:0] loader_ctx_wr_addr, loader_wram_wr_addr;
  logic [127:0] loader_ctx_wr_data;
  logic [767:0] loader_wram_wr_data;
  logic [31:0] loader_words_written;
  logic host_dma_stream_out_ready;
  logic core_dma_route_start;
  logic [1:0] core_dma_route_target;
  logic [31:0] core_dma_route_base;
  logic [31:0] core_dma_route_length;
  assign core_dma_stream_in_valid = dma_input_valid;
  assign core_dma_stream_in_data = dma_input_data;
  // A new internal read beat can be accepted when the previous 128-bit beat
  // is empty, or when its high 64-bit half is being consumed this cycle.
  assign host_dma_stream_out_ready = !dma_output_valid ||
    (dma_output_valid && host_out_ready && dma_output_half && !action_out_valid);
  // Once a routed read starts, its response beats are consumed by the loader;
  // otherwise they remain visible on the tagged host output stream.
  assign core_dma_stream_out_ready = loader_busy ? loader_stream_ready :
                                     host_dma_stream_out_ready;

  assign cmd_word = host_in_data;
  assign desc_id = host_desc_id;
  // The package stream carries the compact descriptor sideband in its low
  // 16 bits; the full descriptor remains in the compiler-generated memory.
  assign desc_data = host_in_data[15:0];
  assign cmd_valid = host_in_valid && (host_in_kind == 3'd0);
  assign desc_valid = cmd_valid;
  assign activation_data = host_in_data;
  assign weight_data = host_in_data;
  assign activation_valid = host_in_valid && (host_in_kind == 3'd1);
  assign weight_valid = host_in_valid && (host_in_kind == 3'd2);
  assign core_sideband_valid = host_in_valid && (host_in_kind == 3'd5);
  assign core_sideband_last = (sideband_beat == 3'd7);
  // A calibration entry needs 80 bits (index + three FP16 scales + bias), so
  // the package stream sends it as two 64-bit beats.  The second beat fires a
  // single-cycle write into the on-chip scale/bias table.
  assign core_scale_load_valid = host_in_valid && host_in_ready &&
                                 (host_in_kind == 3'd6) && scale_half;
  assign core_scale_load_index = scale_index_latched;
  assign core_scale_load_a = scale_a_latched;
  assign core_scale_load_w = scale_w_latched;
  assign core_scale_load_out = scale_out_latched;
  assign core_scale_load_bias = $signed(host_in_data[31:0]);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) sideband_beat <= 3'd0;
    else if (core_sideband_valid && core_sideband_ready) begin
      if (sideband_beat == 3'd7) sideband_beat <= 3'd0;
      else sideband_beat <= sideband_beat + 3'd1;
    end
  end

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      scale_half <= 1'b0;
      scale_index_latched <= '0;
      scale_a_latched <= 16'h3c00;
      scale_w_latched <= 16'h3c00;
      scale_out_latched <= 16'h3c00;
    end else if (host_in_valid && host_in_ready && host_in_kind == 3'd6) begin
      if (!scale_half) begin
        scale_index_latched <= host_in_data[11:0];
        scale_a_latched <= host_in_data[27:12];
        scale_w_latched <= host_in_data[43:28];
        scale_out_latched <= host_in_data[59:44];
        scale_half <= 1'b1;
      end else begin
        scale_half <= 1'b0;
      end
    end
  end

  always_comb begin
    case (host_in_kind)
      3'd0: host_in_ready = cmd_ready && desc_ready;
      3'd1: host_in_ready = activation_ready;
      3'd2: host_in_ready = weight_ready;
      3'd3, 3'd4: host_in_ready = !action_valid;
      3'd5: host_in_ready = core_sideband_ready;
      3'd6: host_in_ready = core_scale_load_ready;
      3'd7: host_in_ready = !dma_input_valid;
      default: host_in_ready = 1'b0;
    endcase
  end

  // Assemble one 112-bit action input from two tagged host beats.
  logic action_half;
  logic [63:0] action_low;
  logic [47:0] action_high;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      action_half <= 1'b0;
      action_low <= '0;
      action_high <= '0;
      action_valid <= 1'b0;
    end else begin
      if (host_in_valid && host_in_ready && host_in_kind == 3'd3) begin
        action_low <= host_in_data;
        action_half <= 1'b1;
        action_valid <= 1'b0;
      end
      if (host_in_valid && host_in_ready && host_in_kind == 3'd4 && action_half) begin
        action_high <= host_in_data[47:0];
        action_half <= 1'b0;
        action_valid <= 1'b1;
      end
      if (action_valid && action_ready) action_valid <= 1'b0;
    end
  end
  assign action_data = {action_high, action_low};

  // The inner core parses the sideband once and exports the routed DMA
  // fields.  This avoids parsing a second, potentially different copy of the
  // descriptor in the package wrapper.
  assign loader_start = core_dma_route_start;
  assign loader_target = core_dma_route_target;

  tvla_dma_ctx_wram_loader u_dma_loader (
    .clk(clk), .rst_n(rst_n), .start(loader_start), .target(loader_target),
    .base_addr(core_dma_route_base[9:0]), .length_bytes(core_dma_route_length),
    .busy(loader_busy), .done(loader_done),
    .stream_valid(core_dma_stream_out_valid),
    .stream_ready(loader_stream_ready), .stream_data(core_dma_stream_out_data),
    .ctx_wr_en(loader_ctx_wr_en), .ctx_wr_addr(loader_ctx_wr_addr),
    .ctx_wr_data(loader_ctx_wr_data), .wram_wr_en(loader_wram_wr_en),
    .wram_wr_addr(loader_wram_wr_addr), .wram_wr_data(loader_wram_wr_data),
    .words_written(loader_words_written)
  );

  // Serialize the 112-bit action result on the same host output stream.
  logic [1:0] action_word_index;
  assign action_out_ready = host_out_ready && action_out_valid &&
                            !dma_output_valid && (action_word_index == 2'd1);
  // DMA read payload has priority over action output.  It uses kinds 2/3 on
  // the output stream; action output keeps the historical kinds 0/1.
  assign host_out_valid = dma_output_valid || action_out_valid;
  assign host_out_kind = dma_output_valid ?
                         (dma_output_half ? 3'd3 : 3'd2) :
                         ((action_word_index == 2'd0) ? 3'd0 : 3'd1);
  assign host_out_data = dma_output_valid ?
                         (dma_output_half ? dma_output_data[127:64] : dma_output_data[63:0]) :
                         ((action_word_index == 2'd0) ? action_target[63:0] :
                          {16'd0, action_target[111:64]});
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) action_word_index <= 2'd0;
    else if (action_out_valid && host_out_ready) begin
      if (action_word_index == 2'd0) action_word_index <= 2'd1;
      else action_word_index <= 2'd0;
    end
  end

  // Pack two tagged 64-bit host beats into one DMA write beat.  The valid
  // register is held until the DMA controller accepts it, so backpressure
  // from AXI cannot lose a payload word.
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      dma_input_valid <= 1'b0;
      dma_input_half <= 1'b0;
      dma_input_low <= '0;
      dma_input_data <= '0;
    end else begin
      if (dma_input_valid && core_dma_stream_in_ready)
        dma_input_valid <= 1'b0;
      if (host_in_valid && host_in_ready && host_in_kind == 3'd7) begin
        if (!dma_input_half) begin
          dma_input_low <= host_in_data;
          dma_input_half <= 1'b1;
        end else begin
          dma_input_data <= {host_in_data, dma_input_low};
          dma_input_valid <= 1'b1;
          dma_input_half <= 1'b0;
        end
      end
    end
  end

  // Split each internal DMA read beat into two host output beats.  This is a
  // real payload path; unlike the previous v7 tie-off, no zero data is
  // manufactured when a DMA_WRITE command is active.
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      dma_output_valid <= 1'b0;
      dma_output_half <= 1'b0;
      dma_output_data <= '0;
    end else begin
      if (core_dma_stream_out_valid && core_dma_stream_out_ready) begin
        dma_output_data <= core_dma_stream_out_data;
        dma_output_valid <= 1'b1;
        dma_output_half <= 1'b0;
      end else if (dma_output_valid && host_out_ready) begin
        if (!dma_output_half)
          dma_output_half <= 1'b1;
        else
          dma_output_valid <= 1'b0;
      end
    end
  end

  assign host_done = replay_done;
  assign host_observe = architecture_observe;

  // The board-facing interface is 64 bits wide while the internal DMA beat
  // is 128 bits.  The bridge below packs two DDR read beats into one AXI R
  // beat and sends one internal write beat as two external data beats.  The
  // old wrapper forwarded only the low 64 bits, which silently discarded half
  // of every write.
  logic rd_first_valid, rd_pair_valid;
  logic [63:0] rd_first_data;
  logic [127:0] rd_pair_data;
  logic rd_pair_last;
  logic [8:0] rd_beats_left;
  logic wr_hold_valid, wr_half;
  logic [127:0] wr_hold_data;
  logic wr_hold_last;
  logic wr_resp_hold;
  logic wr_pair_wait_resp;

  assign core_arready = 1'b1;
  assign core_rvalid = rd_pair_valid;
  assign core_rdata = rd_pair_data;
  assign core_rlast = rd_pair_last;
  // First half can be accepted into the packing register.  The second half
  // is accepted only when the internal AXI R channel can consume the pair.
  assign ddr_read_ready = !rd_pair_valid && (!rd_first_valid || core_rready);

  assign core_awready = 1'b1;
  assign core_wready = !wr_hold_valid && !wr_resp_hold;
  assign ddr_write_valid = wr_hold_valid;
  assign ddr_write_data = wr_half ? wr_hold_data[127:64] : wr_hold_data[63:0];
  assign core_bvalid = wr_resp_hold;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rd_first_valid <= 1'b0;
      rd_pair_valid <= 1'b0;
      rd_first_data <= '0;
      rd_pair_data <= '0;
      rd_pair_last <= 1'b0;
      rd_beats_left <= '0;
      wr_hold_valid <= 1'b0;
      wr_half <= 1'b0;
      wr_hold_data <= '0;
      wr_hold_last <= 1'b0;
      wr_resp_hold <= 1'b0;
      wr_pair_wait_resp <= 1'b0;
    end else begin
      if (core_arvalid && core_arready)
        rd_beats_left <= {1'b0, core_arlen} + 1'b1;
      if (core_rvalid && core_rready) begin
        rd_pair_valid <= 1'b0;
        if (rd_beats_left != 0) rd_beats_left <= rd_beats_left - 1'b1;
      end
      if (ddr_read_valid && ddr_read_ready) begin
        if (!rd_first_valid) begin
          rd_first_data <= ddr_read_data;
          rd_first_valid <= 1'b1;
        end else begin
          rd_pair_data <= {ddr_read_data, rd_first_data};
          rd_pair_last <= (rd_beats_left <= 1);
          rd_pair_valid <= 1'b1;
          rd_first_valid <= 1'b0;
        end
      end

      if (core_wvalid && core_wready) begin
        wr_hold_data <= core_wdata;
        wr_hold_last <= core_wlast;
        wr_hold_valid <= 1'b1;
        wr_half <= 1'b0;
      end
      if (ddr_write_valid && ddr_write_ready) begin
        if (!wr_half) wr_half <= 1'b1;
        else begin
          wr_half <= 1'b0;
          wr_hold_valid <= 1'b0;
          if (wr_hold_last) wr_pair_wait_resp <= 1'b1;
        end
      end
      // AXI B is a response to the whole burst, not to each 64-bit half (or
      // each internal 128-bit beat).  Ignore early board-side pulses and
      // latch the response only after the last pair of the burst.
      if (ddr_write_resp_valid && wr_pair_wait_resp) begin
        wr_resp_hold <= 1'b1;
        wr_pair_wait_resp <= 1'b0;
      end
      if (core_bvalid && core_bready) wr_resp_hold <= 1'b0;
    end
  end

  tvla_complete_model_top #(
    .ROWS(ROWS), .PCOLS(PCOLS), .DESC_W(DESC_W), .DESC_ID_W(DESC_ID_W)
  ) u_core (
    .clk(clk), .rst_n(rst_n), .cmd_word(cmd_word), .cmd_valid(cmd_valid),
    .cmd_ready(cmd_ready), .desc_valid(desc_valid), .desc_ready(desc_ready),
    .desc_id(desc_id), .desc_data(desc_data),
    .sideband_valid(core_sideband_valid), .sideband_ready(core_sideband_ready),
    .sideband_data(host_in_data), .sideband_last(core_sideband_last),
    .scale_load_valid(core_scale_load_valid), .scale_load_ready(core_scale_load_ready),
    .scale_load_index(core_scale_load_index), .scale_load_a(core_scale_load_a),
    .scale_load_w(core_scale_load_w), .scale_load_out(core_scale_load_out),
    .scale_load_bias(core_scale_load_bias),
    .activation_data(activation_data), .activation_valid(activation_valid),
    .activation_ready(activation_ready), .weight_data(weight_data),
    .weight_valid(weight_valid), .weight_ready(weight_ready),
    .feed_pulse(host_feed_pulse), .drain_row(host_drain_row),
    .action_data(action_data), .action_valid(action_valid),
    .action_ready(action_ready), .action_out_valid(action_out_valid),
    .action_out_ready(action_out_ready), .action_target(action_target),
    .action_gripper(action_gripper), .action_step(action_step),
    .replay_done(replay_done), .architecture_observe(architecture_observe),
    .m_axi_arvalid(core_arvalid), .m_axi_arready(core_arready),
    .m_axi_araddr(core_araddr), .m_axi_arlen(core_arlen),
    .m_axi_rvalid(core_rvalid), .m_axi_rdata(core_rdata),
    .m_axi_rlast(core_rlast), .m_axi_rready(core_rready),
    .m_axi_awvalid(core_awvalid), .m_axi_awready(core_awready),
    .m_axi_awaddr(core_awaddr), .m_axi_awlen(core_awlen),
    .m_axi_wvalid(core_wvalid), .m_axi_wready(core_wready),
    .m_axi_wdata(core_wdata), .m_axi_wstrb(core_wstrb),
    .m_axi_wlast(core_wlast), .m_axi_bvalid(core_bvalid),
    .m_axi_bready(core_bready),
    .dma_stream_out_valid(core_dma_stream_out_valid),
    .dma_stream_out_ready(core_dma_stream_out_ready),
    .dma_stream_out_data(core_dma_stream_out_data),
    .dma_stream_in_valid(core_dma_stream_in_valid),
    .dma_stream_in_ready(core_dma_stream_in_ready),
    .dma_stream_in_data(core_dma_stream_in_data),
    .external_ctx_wr_en(loader_ctx_wr_en),
    .external_ctx_wr_addr(loader_ctx_wr_addr),
    .external_ctx_wr_data(loader_ctx_wr_data),
    .external_wram_wr_en(loader_wram_wr_en),
    .external_wram_wr_addr(loader_wram_wr_addr),
    .external_wram_wr_data(loader_wram_wr_data),
    .dma_route_start(core_dma_route_start),
    .dma_route_target(core_dma_route_target),
    .dma_route_base(core_dma_route_base),
    .dma_route_length(core_dma_route_length)
  );
endmodule
`endif
